### ISSUE TITLE
About the File Directory and run error on gusssian_refiner.py

### ISSUE THREAD

**Issue by VillardX** [Barrybarry-Smith/PixelGaussian#1]
Hi, thanks for your great works!

But your PixelGaussian project file directory is different from mvsplat, where is the "src" file directory?

When I adjust the file directory as MVSplat porject and run it on my own dataset, I get an error after running sereveral thousand steps at *model/encoder/adapter/gusssian\_refiner.py*
![33f3306e5c81925d72ef3e30fc1cad28](https://github.com/user-attachments/assets/97a14aa6-f114-4d84-b3bf-5ed10d042049)

The *anchor\_idxs* does not exist in MVSplat project. I check the value of *N* and *self.num_anchors=6400*, It seems reasonable because N is still larger than 6400 when getting the error.

Could you provide some advice on this?

Best regards, 
Villardx

**Comment by Barrybarry-Smith** [comment]
Hi, thanks for your valuable feedback!

Currently, this codebase is still undergoing refinement, and I'll submit the final version as soon as possible. As for the issue you mentioned, can you provide the resolution of your inputs? I'll look into it if I can replicate the problem.

**Comment by VillardX** [comment]
Thanks for reply.
After updating the config file, I can run the train code on my customed data (batchsize=1). 
However, when I change the batchsize to 2, it gets the error as follows

![image](https://github.com/user-attachments/assets/85f99834-0392-4cb1-9ca1-9861b0d6a655)


Seems that the *keypoint_scorer.py* get the error, how to modify it?

Thanks

**Comment by Barrybarry-Smith** [comment]
Sorry but there are some bugs, we will update the full version of code and model no later than the acceptance of the paper.
