### ISSUE TITLE
tau_low&tau_high only rely on gaussian scores?

### ISSUE THREAD

**Issue by wangxuewen99** [Barrybarry-Smith/PixelGaussian#3]
tau_low&tau_high only rely on gaussian scores? updated scores not used?

https://github.com/Barrybarry-Smith/PixelGaussian/blob/3bc1f963d3d08fb4d14fc3ad56bcfab8418c2b5b/model/encoder/adapter/cascade_gaussian_adapter.py#L91

**Comment by Barrybarry-Smith** [comment]
Apologize that I had mistakenly uploaded the wrong version of some files, which has been fixed in the latest commit. Thank you for pointing out!
